"""
models/inference.py
===================
Standardized inference module for SatQuery AI.

Exposes ONE primary clean function:
    answer_question(image_path: str, question: str) -> str

Loads the fine-tuned LoRA model weights from models/checkpoints/blip_rs_lora
(falling back to Salesforce/blip-vqa-base if unadapted). Caches model and processor
in memory for fast, low-latency repeated queries across agent and API workflows.
"""

import os
import sys
from pathlib import Path
from typing import Optional
from PIL import Image
import torch

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Global caches for lazy loading
_CACHED_MODEL = None
_CACHED_PROCESSOR = None
_CACHED_DEVICE = None
_CHECKPOINT_DIR = PROJECT_ROOT / "models" / "checkpoints" / "blip_rs_lora"
_BASE_MODEL_NAME = "Salesforce/blip-vqa-base"


def _get_device() -> torch.device:
    """Selects CUDA GPU if available, else CPU."""
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _load_model_and_processor():
    """
    Lazy loader for the vision-language model and processor.
    Loads the LoRA adapted checkpoint if present; otherwise loads the base model.
    """
    global _CACHED_MODEL, _CACHED_PROCESSOR, _CACHED_DEVICE

    if _CACHED_MODEL is not None and _CACHED_PROCESSOR is not None:
        return _CACHED_MODEL, _CACHED_PROCESSOR, _CACHED_DEVICE

    from transformers import BlipProcessor, BlipForQuestionAnswering
    from peft import PeftModel

    _CACHED_DEVICE = _get_device()
    print(f"[*] Initializing VLM on device: {_CACHED_DEVICE}...")

    # Load processor
    if (_CHECKPOINT_DIR / "preprocessor_config.json").is_file():
        processor = BlipProcessor.from_pretrained(str(_CHECKPOINT_DIR))
    else:
        processor = BlipProcessor.from_pretrained(_BASE_MODEL_NAME)

    # Load base model
    base_model = BlipForQuestionAnswering.from_pretrained(_BASE_MODEL_NAME)

    # Load adapted LoRA weights if checkpoint exists
    adapter_weights = _CHECKPOINT_DIR / "adapter_model.safetensors"
    adapter_bin = _CHECKPOINT_DIR / "adapter_model.bin"
    if adapter_weights.is_file() or adapter_bin.is_file():
        print(f"[+] Loading adapted remote sensing LoRA weights from {_CHECKPOINT_DIR}...")
        model = PeftModel.from_pretrained(base_model, str(_CHECKPOINT_DIR))
    else:
        print(f"[!] Warning: No LoRA checkpoint found at {_CHECKPOINT_DIR}. Using base model {_BASE_MODEL_NAME}.")
        model = base_model

    model.to(_CACHED_DEVICE)
    model.eval()

    _CACHED_MODEL = model
    _CACHED_PROCESSOR = processor
    return _CACHED_MODEL, _CACHED_PROCESSOR, _CACHED_DEVICE


def answer_question(image_path: str, question: str) -> str:
    """
    Answers a natural language query regarding a remote sensing satellite image.

    Args:
        image_path (str): Absolute or relative path to the image file (.png, .jpg, .tif).
        question (str): Query prompt regarding the image content, land cover, or scene.

    Returns:
        str: Concise natural language text answer generated by the adapted VLM.
    """
    resolved_path = Path(image_path)
    if not resolved_path.is_absolute():
        resolved_path = (PROJECT_ROOT / resolved_path).resolve()

    if not resolved_path.is_file():
        return f"Error: Image file not found at '{image_path}'"

    try:
        image = Image.open(resolved_path).convert("RGB")
    except Exception as e:
        return f"Error opening image file '{image_path}': {e}"

    try:
        model, processor, device = _load_model_and_processor()

        # Tokenize and encode multimodal inputs
        inputs = processor(
            images=image,
            text=question,
            return_tensors="pt",
        ).to(device)

        # Autoregressive generation
        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=50,
                num_beams=3,
                early_stopping=True,
            )

        # Decode answer tokens
        answer = processor.decode(output_ids[0], skip_special_tokens=True).strip()
        return answer if answer else "No discernible feature detected."

    except Exception as e:
        return f"Inference error: {str(e)}"


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Query the adapted satellite VLM.")
    parser.add_argument("--image", type=str, required=True, help="Path to satellite image")
    parser.add_argument("--question", type=str, required=True, help="Question to ask")
    args = parser.parse_args()

    print(f"\nImage: {args.image}")
    print(f"Question: {args.question}")
    ans = answer_question(args.image, args.question)
    print(f"Answer: {ans}\n")
